//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupClient
    {
        public System.Guid id { get; set; }
        public System.Guid groupid { get; set; }
        public System.Guid clientid { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Group Group { get; set; }
    }
}
