//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.GroupClient = new HashSet<GroupClient>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public System.Guid trainer { get; set; }
        public System.Guid training { get; set; }
        public int clientmax { get; set; }
        public int clientsnow { get; set; }
        public string description { get; set; }
    
        public virtual Trainer Trainer1 { get; set; }
        public virtual Training Training1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupClient> GroupClient { get; set; }
    }
}
