//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid id { get; set; }
        public System.Guid type { get; set; }
        public string msg { get; set; }
        public bool status { get; set; }
        public System.Guid sender { get; set; }
        public System.Guid receiver { get; set; }
        public string time { get; set; }
        public Nullable<System.Guid> trainingid { get; set; }
        public Nullable<System.Guid> groupid { get; set; }
    
        public virtual Notificationtype Notificationtype { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
