//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingClient
    {
        public System.Guid id { get; set; }
        public System.Guid training { get; set; }
        public System.Guid client { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Training Training1 { get; set; }
    }
}
